### ISSUE TITLE
Gets initial values and that’s it - never updates

### ISSUE THREAD

**Issue by ballakers** [yo-han/Home-Assistant-Carelink#19]
Even after reloading a few times after 15hrs the values just don’t change - she’s good with her blood sugars but not that good lol. Maybe new carelink software etc no longer works with your pull/polling methods?

**Comment by yo-han** [comment]
Most syncing issues occur between sensor, pump, app and carelink. This integration only pulls the latest data from carelink and shows it as a set of sensors. I see some values change every 5 minutes, others a lot less. Sometimes the app stops communicating with carelink and thats when the straigt lines in the graphs come in. 

What pump are you using and do you have a sensor too?

**Comment by ballakers** [comment]
Thanks for the reply and for your work on this!  She has the 770g pump (pretty sure 670 was the previous) and the guardian 3 sensor. Maybe too many other radio waves causing interference haha - I will see if I can make her devices sync up better and give it another shot.

**Comment by yo-han** [comment]
Hmm. I can only confirm this integration works with the 780G right now. But when data is uploaded correct to Carelink I don't see why it shouldn't work. Medtronic pushed an update for the app with connectivity fixes and for what we saw this is a great improvement. Way more stable now. Hope this works for you too.

**Comment by yo-han** [comment]
Finally found some time to look at the problem. Another user forked my repo and made some interesting changes. I merged them back and made some extra changes. If you upgrade to 2023.x.x version of HA I think everything should work a lot better. If you want to try please download the beta release: https://github.com/yo-han/Home-Assistant-Carelink/releases/tag/2023.3.0-rc1
