### ISSUE TITLE
 the integration status changes to a configuration error

### ISSUE THREAD

**Issue by darksideonDM1** [yo-han/Home-Assistant-Carelink#20]
Hello,
after entering the data to the carelink account - the integration status changes to a configuration error. The log shows that the integration has connected to the account because you can see DEBUG (MainThread) [custom_components.carelink] Finished fetching carelink data in 26.615 seconds (success: True). I have installed HA core 2022.6.2.
Please let me know what I can do to make the integration work.

**Comment by darksideonDM1** [comment]
trouble resolved. update ha:)

**Comment by yo-han** [comment]
Ah yes, I should update the readme to note that I only testen with version 2022.12.0 and later. That's when I made this integration.
