### ISSUE TITLE
Errory whilst initializing: 'Retrying Setup: Greenwich Mean Time'

### ISSUE THREAD

**Issue by moonbrushed** [yo-han/Home-Assistant-Carelink#3]
Whilst setting up the integration in home assistant after entering my care partner details, I just get the following error in an endless loop whilst initializing....'Retrying Setup: Greenwich Mean Time'

**Comment by yo-han** [comment]
You're absolutely right. I made a fix and created a new version. The update should be available through your home assistant soon.

**Comment by moonbrushed** [comment]
Thanks for fixing so quickly! However, now I'm getting the message 'Retrying Setup: gstBatteryLevel' in the same place.

**Comment by yo-han** [comment]
Ah wow. Great test case. Do you use a pump with sensor or without? The gstBatteryLevel is the battery of the sensor. It's clear I should do a better job in adding fallback values for each sensor as are not always available as it seems.

**Comment by moonbrushed** [comment]
I don't use a sensor...I think I may have done in the past but all the sensor things are disabled in the pump currently.

**Comment by yo-han** [comment]
Allright. Makes sense then. I made a new release with fallbacks for all values this time. Hope this helps.

**Comment by moonbrushed** [comment]
Hi there. Thanks for the quick responses. Have updated to 12.4 but am still getting the same battery message.

**Comment by yo-han** [comment]
It seems to be a bit more difficult issue then expected. I'll will give a more thorough look later this weekend. First I need to find a way to reproduce the error in my dev environment so I can debug the issue better. Thanks for the feedback and I'm sorry for the inconvenience.

**Comment by yo-han** [comment]
A new release is live with a lot of fixes and features. Hope this helps with the issues you experienced. If not please let me know.
