### ISSUE TITLE
Error with setting up Integration

### ISSUE THREAD

**Issue by bvdkerkhof** [yo-han/Home-Assistant-Carelink#30]
Running latest version through HACS.

When setting up the Integration I enter my Username/Password and CountryCode (nl). When Trying to Save/Connect it hits me directly with an "Unknown error". 

Running HA 2023.5.4
Log gives me:
`Logger: custom_components.carelink.config_flow
Source: custom_components/carelink/config_flow.py:35
Integration: carelink
First occurred: 12:53:37 (2 occurrences)
Last logged: 12:56:37

Unexpected exception
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/carelink/config_flow.py", line 61, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/home/homeassistant/.homeassistant/custom_components/carelink/config_flow.py", line 35, in validate_input
    data["username"], data["password"], data["country"], data["patientId"]
KeyError: 'patientId'`

**Comment by yo-han** [comment]
Ai, my bad. Stupid mistake there. I made a quick fix and just released it. The update should be available shortly.

**Comment by bvdkerkhof** [comment]
Thanks, updated and restarted HA, this solved the issue!
