### ISSUE TITLE
No readings

### ISSUE THREAD

**Issue by meluvalli** [yo-han/Home-Assistant-Carelink#58]
Hello.  I'm in the US and tried using this HA component, but when I setup the "device" in HA, it pulls the patient correctly, shows me info about the pump, but there are no CGM readings (Last glucose level mg/dl = unknown).  

I tried logging in with follower account and patient account and same exact results.

Any thoughts?

![Screenshot 2024-01-14 025501](https://github.com/yo-han/Home-Assistant-Carelink/assets/8729476/2579ac17-dd30-4081-af7c-b512407fda1a)

**Comment by meluvalli** [comment]
Ok.  Found out that my wife's pump isn't connected the phone currently.  It got disconnected and is stuck "reconnecting to pump"..  This is why there is no "current" data.

So, now I have a feature request...   Would be nice if it would pull the last "known" numbers...  This is in the data file if I use the python client to download the data...  So, would be nice if it pulled the latest "known" number and time stamp when it was.  Once my wife's pump reconnects, I am hopeful this plugin will work and it will get the current numbers.  Meanwhile, I can create a new sensor to auto update with the latest number manually!

**Comment by yo-han** [comment]
Hi @meluvalli, yes this is exactly how it works now. The disconnection of the pump, when batteries are dead or by bad connection, is a well known issue. I like the idea of keeping the latest know value of the most important sensors I't also very important to show the timestamp of this last measurement to prevent people from miscalculation with very old data.

**Comment by meluvalli** [comment]
Correct.  I would envision it having something like “current reading” and
then another value named “last known reading” or something like that so
they are very different.  That’s what I would recommend anyways.  Then both
with time stamps.

**Comment by greenhawk89** [comment]
Have you guys been able to figure out how to get a "last known reading" going? That would be great. I often don't know if it's the pump failing to connect, or if there's some kind of problem with the carelink integration.

**Comment by sedy89** [comment]
![grafik](https://github.com/yo-han/Home-Assistant-Carelink/assets/65983953/591090f5-9b2d-49c6-9f13-d0e7b9620da7)

I am testing some changes at the moment, including a new sensor that shows the timestamp of the last valid glucose reading.
As you can see, the reading is already 25 min old but is still shown. The "Last update" is the old sensor that basically just shows the 5min update periode from the pump.

That's what you were looking for, right?

**Comment by meluvalli** [comment]
Yep!  That sounds right!

Thank you!

**Comment by yo-han** [comment]
The new PR by @sedy89 is merged and released as a [pre-release](https://github.com/yo-han/Home-Assistant-Carelink/releases/tag/2024.2.0-rc1). If you like to test the release check the beta releases in Home Assistant for this add-on to try it out.

**Comment by meluvalli** [comment]
Thanks!  I have installed it, and will let you know how it goes once the pump hasn't updated...  (Probably when my wife replaces sensor with any luck)

**Comment by meluvalli** [comment]
Works perfectly!  THANK YOU!!!
