### ISSUE TITLE
Token refresh

### ISSUE THREAD

**Issue by sniperdaddy79** [yo-han/Home-Assistant-Carelink#59]
Hello, Could you help me pls. A started to use this Carelink integration, but about every 4-5 days I have to refresh the token, if not all the data will be "unavailable". Am I doing soemthing wrong? Thanks a lot!

**Comment by greenhawk89** [comment]
I am also seeing this with Carelink. It's as if the API key (that we get from the Firefox addon) keeps expiring or something. 

This also ties to the feature request about "show how old of a reading it is" so that the diabetic doesn't end up using stale data to make real-time decisions.

Thanks!!

**Comment by sedy89** [comment]
I also had some problems that my token expired. I am currently testing some updates and since a couple of days it is running just fine. I will create a PR soon

**Comment by yo-han** [comment]
The new PR by @sedy89 is merged and released as a [pre-release](https://github.com/yo-han/Home-Assistant-Carelink/releases/tag/2024.2.0-rc1). If you like to test the release check the beta releases in Home Assistant for this add-on to try it out.
