### ISSUE TITLE
Wrong last glucose level mmol/l

### ISSUE THREAD

**Issue by Lekskog** [yo-han/Home-Assistant-Carelink#62]
I'm running the latest beta version 2024.2.0.1-rc1 but the problem is that it types out the last glucos level as exampel 117,11 mmol/l when it is 11,7 mmol/l

**Comment by bvdkerkhof** [comment]
Also have the same issue running the latest rc and HA 2024.2.0

**Comment by Lekskog** [comment]
> Also have the same issue running the latest rc and HA 2024.2.0

I have solved it by doing a helper template that take the value and divide it by 10

**Comment by yo-han** [comment]
Fixed in the next release
