### ISSUE TITLE
Auto update token

### ISSUE THREAD

**Issue by Lekskog** [yo-han/Home-Assistant-Carelink#64]
Is it possible to auto update token if we insert username/pw and country? Or is it possible to make a script in HA for this?

**Comment by sedy89** [comment]
No, because of the google recaptcha. That's how it was done before the recaptcha was introduced by medtronic.

**Comment by Lekskog** [comment]
> No, because of the google recaptcha. That's how it was done before the recaptcha was introduced by medtronic.

Bummer! Love this integration, it makes it possible to follow my sons blood sugar level in my phone that is not supported by medtronic app
