### ISSUE TITLE
Session Token - What Token to use

### ISSUE THREAD

**Issue by MrRasmus** [yo-han/Home-Assistant-Carelink#72]
Hi, I have the problem that I don't know what to choose when asked for Session Token first time I set it up? I have tried once where it was working for a couple of hours and then suddenly stopped working. 
I have made the logindata.json which it says in your guide.
![Screenshot_1](https://github.com/yo-han/Home-Assistant-Carelink/assets/43639948/a9ac0e2b-859c-41f0-9541-5535465abf4a)

**Comment by sedy89** [comment]
Try to download the latest beta release in HA and follow the instructions on the main page of this repo. Until now, it seems to be very stable without any issue with the token.
