### ISSUE TITLE
Python Script support for MacOS

### ISSUE THREAD

**Issue by markus76** [yo-han/Home-Assistant-Carelink#75]
Hi,
is it planned to support MacOS in script?
If you need someone to test, i'am here :-)

<img width="875" alt="image" src="https://github.com/yo-han/Home-Assistant-Carelink/assets/15011452/355e5dbb-4d6f-4fc9-b7d4-f47a421f9e7e">

regards 
Markus

**Comment by sedy89** [comment]
Hi Markus,
Could you check this [link](https://www.tutorialspoint.com/how-to-get-firefox-working-with-selenium-webdriver-on-mac-osx) and make sure you have the geckodriver installed?
Once you have that, you can change the code of the python script and use the same lines as for the windows platform. The code is in the do_captcha function at the beginning.

It might already work, but it was never tested.

**Comment by markus76** [comment]
Thank you for your response... 
It works 💯 
<img width="563" alt="image" src="https://github.com/yo-han/Home-Assistant-Carelink/assets/15011452/4733bb48-14c3-4394-b5b5-fcd3840c2ea1">

Thanks for your support
