### ISSUE TITLE
INFO - What is conduit battery / levels?

### ISSUE THREAD

**Issue by warmfire540** [yo-han/Home-Assistant-Carelink#83]
Hey,

i'm setting up some alerting to help w/ few things.  What are the "conduit" data points?
We get the sensor/pump, I'm not sure what is conduit exactly, not seeing much info from Medtronic.

looks like it uses conduitBatteryLevel, etc. from the payload

**Comment by yo-han** [comment]
These are glucose sensor parameters.  `conduitBatteryLevel` is the battery level of the sensor.

**Comment by warmfire540** [comment]
hey - the diagnostics have pump / sensor settings already.  What do the 4 conduit ones refer too? sorry my integration having some issues atm, going to dig at the issue later..

However in your screenshot you have the THREE battery levels.  So just trying to see what the third one is vs pump/sensor combo.

<img width="406" alt="image" src="https://github.com/yo-han/Home-Assistant-Carelink/assets/19420884/03b400c8-759b-4848-8dfd-9cec2a5205a1">

**Comment by yo-han** [comment]
You're right. I checked and the conduit is the device that's used to send the data from the pump to Medtronic. In most cases this is a phone. I hope this makes things more clear.

**Comment by warmfire540** [comment]
Ok, I think that clears it up.  Thanks!
